"""
Clean provider abstraction for the chat backend.

The rest of the application only ever depends on `AIProvider.stream_completion`, so
swapping the placeholder for a real backend (Fireworks AI, OpenAI-compatible, etc.)
never touches UI or database code.
"""
from __future__ import annotations

import json
import random
import time
from abc import ABC, abstractmethod
from typing import Iterator, List

import requests

from app import config
from app.models.message import Message


class AIProvider(ABC):
    """Base interface every backend must implement."""

    @abstractmethod
    def stream_completion(self, messages: List[Message]) -> Iterator[str]:
        """Yield successive text chunks that make up the assistant's reply."""
        raise NotImplementedError

    def suggest_title(self, first_user_message: str) -> str:
        """Best-effort short title from the first exchange. Providers may override
        this with a real model call; the default just trims the raw text."""
        text = " ".join(first_user_message.strip().split())
        return (text[:42] + "…") if len(text) > 42 else (text or "New chat")


class PlaceholderProvider(AIProvider):
    """
    Simulates a streaming assistant with zero network dependency, so the full UI
    (typing indicator, streaming animation, stop button, markdown/code rendering)
    can be exercised end-to-end without any API key.
    """

    _CANNED_INTRO = [
        "Sure — here's what I'd suggest:",
        "Good question. Let's break it down:",
        "Here's a quick rundown:",
        "Happy to help with that.",
    ]

    def stream_completion(self, messages: List[Message]) -> Iterator[str]:
        last_user = next(
            (m.content for m in reversed(messages) if m.role.value == "user"), ""
        )
        reply = self._build_reply(last_user)
        # Stream word-by-word to emulate a real token stream.
        words = reply.split(" ")
        for i, word in enumerate(words):
            time.sleep(random.uniform(0.012, 0.045))
            yield word + ("" if i == len(words) - 1 else " ")

    def _build_reply(self, user_text: str) -> str:
        intro = random.choice(self._CANNED_INTRO)
        lower = user_text.lower()

        if any(k in lower for k in ("code", "python", "function", "script", "bug")):
            return (
                f"{intro}\n\n"
                "Here's a small, self-contained example:\n\n"
                "```python\n"
                "def greet(name: str) -> str:\n"
                "    \"\"\"Return a friendly greeting.\"\"\"\n"
                "    return f\"Hello, {name}! 👋\"\n\n"
                "if __name__ == \"__main__\":\n"
                "    print(greet(\"world\"))\n"
                "```\n\n"
                "A few notes:\n\n"
                "- It's fully type-hinted for clarity.\n"
                "- You can drop this straight into a module and import it.\n"
                "- Let me know if you'd like tests added.\n"
            )

        if any(k in lower for k in ("list", "steps", "how do i", "plan")):
            return (
                f"{intro}\n\n"
                "1. Clarify the goal and constraints.\n"
                "2. Break the work into small, testable steps.\n"
                "3. Build the simplest version that works.\n"
                "4. Iterate based on feedback.\n\n"
                "> Tip: shipping something small and real beats a perfect plan on paper.\n"
            )

        return (
            f"{intro}\n\n"
            f"You said: *\"{user_text.strip()[:120]}\"* — this is placeholder output "
            "from the local demo provider, so responses are simulated rather than "
            "generated by a real model. Wire up `FireworksAIProvider` in "
            "`app/services/ai_service.py` to connect a live backend.\n\n"
            "**Markdown showcase**\n\n"
            "| Feature | Status |\n"
            "|---|---|\n"
            "| Streaming | ✅ |\n"
            "| Tables | ✅ |\n"
            "| Code blocks | ✅ |\n"
        )


class FireworksAIProvider(AIProvider):
    """
    Real backend using the Fireworks AI chat-completions endpoint (OpenAI-compatible
    schema). Fill in `config.FIREWORKS_API_KEY` / `config.FIREWORKS_MODEL` and flip
    `config.ACTIVE_PROVIDER = "fireworks"` to activate.
    """

    def __init__(self, api_key: str | None = None, model: str | None = None):
        self._api_key = api_key or config.FIREWORKS_API_KEY
        self._model = model or config.FIREWORKS_MODEL

    def stream_completion(self, messages: List[Message]) -> Iterator[str]:
        if not self._api_key:
            yield (
                "⚠️ No Fireworks API key configured. Set the `FIREWORKS_API_KEY` "
                "environment variable or edit `app/config.py`."
            )
            return

        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self._model,
            "messages": [m.to_api_dict() for m in messages],
            "stream": True,
            # TODO: expose temperature / max_tokens / top_p as user settings.
            "temperature": 0.7,
        }

        try:
            with requests.post(
                config.FIREWORKS_API_URL,
                headers=headers,
                json=payload,
                stream=True,
                timeout=60,
            ) as response:
                response.raise_for_status()
                for raw_line in response.iter_lines():
                    if not raw_line:
                        continue
                    line = raw_line.decode("utf-8").strip()
                    if not line.startswith("data:"):
                        continue
                    data = line[len("data:"):].strip()
                    if data == "[DONE]":
                        break
                    try:
                        chunk = json.loads(data)
                        delta = chunk["choices"][0]["delta"].get("content", "")
                        if delta:
                            yield delta
                    except (KeyError, IndexError, json.JSONDecodeError):
                        continue
        except requests.RequestException as exc:
            yield f"\n\n⚠️ Request to Fireworks AI failed: {exc}"


def get_active_provider() -> AIProvider:
    """Factory used by the rest of the app — the single seam to swap backends."""
    if config.ACTIVE_PROVIDER == "agent":
        from app.services.agent_provider import AgentProvider  # avoids circular import
        return AgentProvider()
    if config.ACTIVE_PROVIDER == "fireworks":
        return FireworksAIProvider()
    return PlaceholderProvider()
